{
 "title": "ECE1779 Monitor Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_requests_total{job=\"collab_backend\", route != \"/favicon.ico\",method != \"PUT\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"collab_backend\"}[5m])",
     "legendFormat": "{Backend CPU}"
    }
   ]
  },
  {
   "title": "Backend Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"collab_backend\"}",
     "legendFormat": "{Memory Usage}"
    }
   ]
  }
 ]
}